steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'terraformtest'   # Name of your service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip
      sudo unzip terraform.zip -d /usr/local/bin
      terraform version

      terraform init
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
