steps:
- script: |
    curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip
    sudo unzip terraform.zip -d /usr/local/bin
    terraform version
  displayName: 'Install Terraform'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
